"""Encode repository voice WAVs into deterministic 16 kHz IMA ADPCM C data."""

import argparse
import math
from pathlib import Path
import struct
import wave


NAMES = (
    "startup", "peer_join", "peer_leave", "mesh_on", "mesh_off",
    "phone_pairing", "channel_green", "channel_red", "channel_blue",
    "you_are_coordinator", "you_are_participant", "incoming_phone_call",
)
IDS = (
    "STARTUP", "PEER_JOIN", "PEER_LEAVE", "MESH_ENABLED", "MESH_DISABLED",
    "BLUETOOTH_PAIRING", "CHANNEL_GREEN", "CHANNEL_RED", "CHANNEL_BLUE",
    "ROLE_COORDINATOR", "ROLE_PARTICIPANT", "INCOMING_CALL",
)
STEPS = (
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41,
    45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190,
    209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724,
    796, 876, 963, 1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272,
    2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871, 5358, 5894, 6484,
    7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899, 15289, 16818,
    18500, 20350, 22385, 24623, 27086, 29794, 32767,
)
INDEX_DELTA = (-1, -1, -1, -1, 2, 4, 6, 8)


def read_wav(path):
    with wave.open(str(path), "rb") as wav:
        if (wav.getcomptype(), wav.getnchannels(), wav.getsampwidth(), wav.getframerate()) != (
            "NONE", 1, 2, 24000
        ):
            raise ValueError(f"{path}: expected mono 24 kHz 16-bit PCM WAV")
        data = wav.readframes(wav.getnframes())
    if not data:
        raise ValueError(f"{path}: empty WAV")
    return struct.unpack(f"<{len(data) // 2}h", data)


def resample(samples):
    # 24 kHz to 16 kHz, normalized 24-tap windowed sinc at the destination time.
    # The 7.5 kHz cutoff leaves transition room below the new 8 kHz Nyquist.
    result = []
    cutoff = 7500 / 24000
    for out in range((len(samples) * 2 + 1) // 3):
        center = out * 1.5
        first = math.floor(center) - 11
        weighted = norm = 0.0
        for pos in range(first, first + 24):
            distance = center - pos
            if abs(distance) >= 12:
                continue
            sinc = 2 * cutoff if distance == 0 else math.sin(2 * math.pi * cutoff * distance) / (math.pi * distance)
            window = 0.5 + 0.5 * math.cos(math.pi * distance / 12)
            weight = sinc * window
            weighted += samples[min(max(pos, 0), len(samples) - 1)] * weight
            norm += weight
        result.append(max(-32768, min(32767, round(weighted / norm))))
    return result


def encode(samples):
    predictor = index = 0
    output = bytearray()
    for pos, sample in enumerate(samples):
        step = STEPS[index]
        delta = sample - predictor
        code = 8 if delta < 0 else 0
        delta = abs(delta)
        diff = step >> 3
        for bit, portion in ((4, step), (2, step >> 1), (1, step >> 2)):
            if delta >= portion:
                code |= bit
                delta -= portion
                diff += portion
        predictor += -diff if code & 8 else diff
        predictor = max(-32768, min(32767, predictor))
        index = max(0, min(88, index + INDEX_DELTA[code & 7]))
        if pos & 1:
            output[-1] |= code << 4
        else:
            output.append(code)
    return output


def generate(directory):
    lines = ['/* Generated by tools/encode_notifications.py; do not edit. */',
             '#include "audio_prompt.h"', '']
    table = []
    for name, identifier in zip(NAMES, IDS):
        samples = resample(read_wav(directory / f"{name}.wav"))
        data = encode(samples)
        lines.append(f"static const uint8_t prompt_{name}[] = {{")
        for i in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
        lines.append("};")
        table.append(f"    [AUDIO_NOTIFY_{identifier}] = "
                     f"{{prompt_{name}, sizeof(prompt_{name}), {len(samples)}u, 0, 0}},")
    lines.extend(['', 'const audio_prompt_clip_t audio_prompt_clips[AUDIO_NOTIFY_COUNT] = {',
                  *table, '};', ''])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audios", type=Path, default=Path(__file__).resolve().parent.parent / "audios")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = generate(args.audios)
    args.output.write_text(content)


if __name__ == "__main__":
    main()
